### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by JustAKuba** [0x000015/SpaceEngineers-DLC-Bypass#12]
Hey guys, I just tried to apply this on my SE, but everything but decorative pack 2 disappeared, maybe I've done something wrong, but just in case, I want to report it to you :)

What I've done:

- Downloaded zip file

- Dropped files CubeBlocks and  BlockCategories into Data

- Added Mod file into Mods(AppData etc.)

Thanks for your work 👍

**Comment by 0x000015** [comment]
No worries, I'll be pushing a fix here soon. I've been a bit busy lately so haven't been able to cover it yet.

**Comment by 0x000015** [comment]
Should be fixed now, if you have any more issues feel free to reopen
