### ISSUE TITLE
I demand answer!

### ISSUE THREAD

**Issue by martin951** [0x000015/SpaceEngineers-DLC-Bypass#14]
Hi! First of all thanks for this, the DLC blocks that show up but cannot be used are fkin annoying.

After installing, I am missing some categories from the G menu. For example there is no "Decoration" category + some items are not displayed in the "ALL BLOCKS" list.
Do you think it is related to your mod? Am I missing something? I believe I installed it correctly.

**Comment by 0x000015** [comment]
Have you updated it since today?

**Comment by martin951** [comment]
No, I didn't know closed issue means you updated it. I am going to try that right now, thank you!

**Comment by martin951** [comment]
I do see the categories, however ALL BLOCKS still has a limited listing. Not a biggie tho, thans for oyur effort.

**Comment by 0x000015** [comment]
Limited listing? Could you send a photo? Whenever I tried them out I appeared to have all blocks.

**Comment by martin951** [comment]
![image](https://user-images.githubusercontent.com/15638012/86441310-4bf7a700-bd0c-11ea-8971-84169cc2a292.png)

**Comment by 0x000015** [comment]
As far as I know the DLC blocks don't _actually_ show up in the main default category. Hence the DLC categories show up.

**Comment by martin951** [comment]
![image](https://user-images.githubusercontent.com/15638012/86441497-97aa5080-bd0c-11ea-90ba-5202edf37fd5.png)

**Comment by martin951** [comment]
![image](https://user-images.githubusercontent.com/15638012/86441538-a85ac680-bd0c-11ea-9e31-2686b6426b34.png)

**Comment by martin951** [comment]
^^^^^for example^^^^^^

**Comment by 0x000015** [comment]
Do all the blocks still show in their categories?

**Comment by martin951** [comment]
I think they do

**Comment by 0x000015** [comment]
Should be no issues then. Sounds like its doing what it does normally.

**Comment by martin951** [comment]
Allright
