### ISSUE TITLE
Mod Folder Wrong Name

### ISSUE THREAD

**Issue by therealcrow999** [0x000015/SpaceEngineers-DLC-Bypass#17]
I don't know if they changed it or you put in wrong name, but the mod folder is called Mods and not Mod. Thanks for update.

**Comment by 0x000015** [comment]
Don't worry about the mods its just for uploading to the steam workshop. Don't really recommend though as the last time I did that they gave a ban. (This was before unlisted/private workshop posts)

**Comment by therealcrow999** [comment]
> Don't worry about the mods its just for uploading to the steam workshop. Don't really recommend though as the last time I did that they gave a ban. (This was before unlisted/private workshop posts)

So it is better to do the overwrite method? At one point, I was doing the mod folder to add them to my own save to test them out. I just never did the overwrite, do to every small update that SE comes out with, I might have to reinstall files.

**Comment by 0x000015** [comment]
Overwrite method is mainly just for clients but it may work for servers aswell but I never really tested the mod version. I figured it'd work just the same due to how mods work
