### ISSUE TITLE
Keen Moved CubeBlocks in a Folder

### ISSUE THREAD

**Issue by therealcrow999** [0x000015/SpaceEngineers-DLC-Bypass#2]
I was checking the other day, I don't think this would work anymore. The file layout is different now and Keen moved them into this folder:
C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Data\CubeBlocks

There is a CubeBlocks folder now that they put most things in now.

**Comment by 0x000015** [comment]
I'll look into this. So far the only issues I've seen is where it seems to just auto-reset the cubeblocks files after every restart of the game.

**Comment by 0x000015** [comment]
Okay after doing some testing everything seems to be working correctly. Expect an update soon.
