### ISSUE TITLE
Works for me, but not paint materials.

### ISSUE THREAD

**Issue by collinator24** [0x000015/SpaceEngineers-DLC-Bypass#3]
All of the decoration blocks work for me, however, the paint materials do not. Any way to make it work with the paint. Other than that, it's amazing. Keep up the good work. Cannot believe that keen would do this.

**Comment by 0x000015** [comment]
Doesn't look like there's anyway from what I can tell to allow the armor block skins. My guess since it checks your steam inventory.

**Comment by collinator24** [comment]
Ah, what a shame. It would be nice but at least its got the decoration
blocks. Thanks
