### ISSUE TITLE
Does not work for blueprints

### ISSUE THREAD

**Issue by collinator24** [0x000015/SpaceEngineers-DLC-Bypass#4]
When I save blueprints, none of the Decorations DLC goes with when I paste it in servers, any fixes?

**Comment by 0x000015** [comment]
I don't know if I'll be able to find a fix but I'll take a look.

**Comment by 0x000015** [comment]
Looks like I may have found a fix. I'll be pushing an update here soon. If you can tell me if this fixes it.

**Comment by collinator24** [comment]
I'll try it later today, and let you know.

**Comment by collinator24** [comment]
Issues Fixed. Thanks!
