### ISSUE TITLE
Might Need Updating, Due to Change in DLC 2

### ISSUE THREAD

**Issue by therealcrow999** [0x000015/SpaceEngineers-DLC-Bypass#5]
I believe this needs updated, yesterday 10/30/19 Keen decided to give everyone the small control seat free to everyone and not have it in the deco dlc 2. 

Also I wanted to stay thanks for maintaining this, a very nice fix to get the dlcs.

**Comment by 0x000015** [comment]
Believe I've fixed it, Pushing it now.
